"""add tracker ownership

Revision ID: da63cadda154
Revises: e7728c11624f
Create Date: 2026-09-20 17:46:29.314022
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'da63cadda154'
down_revision: str | None = 'e7728c11624f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackers', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_trackers_owner_id'), 'trackers', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trackers_owner_id'), table_name='trackers')
    op.drop_column('trackers', 'owner_id')
    # ### end Alembic commands ###
